# Generated by Django 5.1.3 on 2024-11-26 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('autor', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('NF', 'NÃO_FICÇÃO'), ('F', 'FICÇÃO')], default='NF', max_length=2)),
                ('lido', models.BooleanField(default=False)),
                ('avaliacao', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
    ]
